apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    name: {{ .Values.configMap.name }}
  namespace: {{ .Values.general.defaultNamespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        type: "governance-metrics"

    scrape_configs:

      - job_name: "live-metrics"
        params:
          mode: [ "live" ]
        static_configs:
          - targets: [ "dlt:80" ]

      - job_name: "static-metrics"
        params:
          mode: [ "static" ]
        static_configs:
          - targets: [ "dlt:80" ]