apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storageVolume.volumeName }}
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi