apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storageVolume.volumeName }}
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi